---
- name: Download rustup installer-script
  get_url:
    url: https://sh.rustup.rs
    dest: /home/kevin/.tmp/rustup-install.sh
    mode: 0740

- name: Install rustup
  script:
    name: /home/kevin/.tmp/rustup-install.sh -y
    creates: /home/kevin/.cargo
    executable: sh

- name: Source the Cargo ENV files
  shell: source /home/kevin/.cargo/env

- name: Add Rust to $PATH (FISH)
  lineinfile:
    path: "/home/kevin/.config/fish/config.fish"
    line: "set -gx PATH /home/kevin/.cargo/bin $PATH"
  when:
    - default_shell == "fish"

- name: Add Rust to $PATH (ZSH)
  lineinfile:
    path: "/home/kevin/.zshrc"
    line: "export PATH=$HOME/.cargo/bin:$PATH"
  when:
    - default_shell == "zsh"

- name: Set Rust Default Toolchain to Nightly
  command: rustup default nightly

- name: Install the additional rust components
  command: "rustup component add {{ item }}"
  ignore_errors: yes
  with_items:
    - rustfmt
    - clippy
    - rls

- name: Install Required System Packages (Ubuntu)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libssl-dev
    - cmake
    - pkg-config
  when: 
    - (ansible_facts.ansible_distribution == "Ubuntu") and (development_machine or development_component_rust_cargo_extras)

# Maybe split these out?
- name: Install All Cargo Extras 
  command: "cargo install {{ item }}"
  with_items:
    - cargo-update 
    - cargo-outdated 
    - cargo-graph 
    - cargo-geiger 
    - cargo-tree 
    - cargo-modules 
    - cargo-edit 
    - cargo-count 
    - cargo-bloat 
    - cargo-cache 
    - ripgrep 
    - exa 
    - skim 
    - mdbook 
    - bat 
    - fd-find 
    - tokei 
    - clog-cli 
    - hexyl   
  when: 
    - development_machine or development_component_rust_cargo_extras

# this will add the line over and over
- name: Copy Rust setting to ZSH profile
  shell: "cat /home/kevin/.dotfiles/zsh/addons/rust.zsh-addon >> /home/kevin/.zshrc"
  when: 
    -|
     desktop_component_dotfiles and 
     default_shell == "zsh"