---
- name: Copy vim settings from dotfiles
  command: "cp -r /home/kevin/.dotfiles/vim /home/kevin/.vim"
  args:
    creates: /home/kevin/.vim
  when: 
    - desktop_component_dotfiles or desktop_machine 

- name: Copy vimrc from dotfiles
  command: "cp /home/kevin/.vim /home/kevin/.vimrc"
  args:
    creates: /home/kevin/.vimrc

- name: Clone vim Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: /home/kevin/.vim/bundle/Vundle.vim

- name: Install vim Plugins
  command: "vim +PluginInstall +qall"
