#!/bin/sh

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one.

cat << EOF
 ${reset}${redf}  ██  ██   ${reset}${greenf}   ██  ██   ${reset}${yellowf}   ██  ██   ${reset}${bluef}   ██  ██   ${reset}${purplef}   ██  ██   ${reset}${cyanf}   ██  ██   ${reset}
 ${reset}${redf}██████████ ${reset}${greenf} ██████████ ${reset}${yellowf} ██████████ ${reset}${bluef} ██████████ ${reset}${purplef} ██████████ ${reset} ${cyanf}██████████ ${reset}
 ${reset}${redf}  ██${boldon}██${boldoff}██   ${reset}${greenf}   ██${boldon}██${boldoff}██   ${reset}${yellowf}   ██${boldon}██${boldoff}██   ${reset}${bluef}   ██${boldon}██${boldoff}██ ${reset}${purplef}     ██${boldon}██${boldoff}██   ${reset}${cyanf}   ██${boldon}██${boldoff}██   ${reset}
 ${reset}${redf}██████████ ${reset}${greenf} ██████████ ${reset}${yellowf} ██████████ ${bluef} ██████████ ${purplef} ██████████ ${reset}${cyanf} ██████████${reset}
 ${reset}${redf}  ██  ██   ${reset}${greenf}   ██  ██   ${reset}${yellowf}   ██  ██   ${reset}${bluef}   ██  ██   ${reset}${purplef}   ██  ██   ${reset}${cyanf}   ██  ██   ${reset}
 ${reset}
EOF
