#!/bin/sh

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one.

cat << EOF
${redf} █=@=█ ${reset} ${greenf}█=@=█ ${reset} ${yellowf}█=@=█ ${reset} ${bluef}█=@=█ ${reset} ${purplef}█=@=█ ${reset} ${cyanf}█=@=█ ${reset}
${redf}  ■ ■  ${reset} ${greenf} ■ ■  ${reset} ${yellowf} ■ ■  ${reset} ${bluef} ■ ■  ${reset} ${purplef} ■ ■  ${reset} ${cyanf} ■ ■  ${reset}
${redf}  =■=  ${reset} ${greenf} =■=  ${reset} ${yellowf} =■=  ${reset} ${bluef} =■=  ${reset} ${purplef} =■=  ${reset} ${cyanf} =■=  ${reset}
EOF

#${boldon}${redf} █   █ ${reset} ${boldon}${greenf}█   █ ${reset} ${boldon}${yellowf}█   █ ${reset} ${boldon}${bluef}█   █ ${reset} ${boldon}${purplef}█   █ ${reset} ${boldon}${cyanf}█   █ ${reset}
#${boldon}${redf}  ■ ■  ${reset} ${boldon}${greenf} ■ ■  ${reset} ${boldon}${yellowf} ■ ■  ${reset} ${boldon}${bluef} ■ ■  ${reset} ${boldon}${purplef} ■ ■  ${reset} ${boldon}${cyanf} ■ ■  ${reset}
#${boldon}${redf}  =■=  ${reset} ${boldon}${greenf} =■=  ${reset} ${boldon}${yellowf} =■=  ${reset} ${boldon}${bluef} =■=  ${reset} ${boldon}${purplef} =■=  ${reset} ${boldon}${cyanf} =■=  ${reset}
