#!/bin/sh

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one.
# ****************************** Building blocks: █ ▓ ▒ ░ ▄ ▀ ▐ ▌ ●  ═ ║ ╔ ╦ ╗ ╚ ╩ ╝ ■ ▬ ▲ ▼ ◄ ►

cat << EOF
${greenf}█         █  ${redf}█         █  ${bluef}█         █  ${purplef}█         █  ${cyanf}█         █
${greenf}█   ▄▄▄   █  ${redf}█   ▄▄▄   █  ${bluef}█   ▄▄▄   █  ${purplef}█   ▄▄▄   █  ${cyanf}█   ▄▄▄   █
${greenf}█▄▄██▀██▄▄█  ${redf}█▄▄██▀██▄▄█  ${bluef}█▄▄██▀██▄▄█  ${purplef}█▄▄██▀██▄▄█  ${cyanf}█▄▄██▀██▄▄█
${greenf}█▀▀█████▀▀█  ${redf}█▀▀█████▀▀█  ${bluef}█▀▀█████▀▀█  ${purplef}█▀▀█████▀▀█  ${cyanf}█▀▀█████▀▀█
${greenf}█   ▀▀▀   █  ${redf}█   ▀▀▀   █  ${bluef}█   ▀▀▀   █  ${purplef}█   ▀▀▀   █  ${cyanf}█   ▀▀▀   █
${greenf}█         █  ${redf}█         █  ${bluef}█         █  ${purplef}█         █  ${cyanf}█         █
${reset}
EOF
