" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
filetype off

" ================ General Config ====================
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set mouse=a

" ================ Vundle ===========================
" Set the runtime path to include Vundle and it's init
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Let Vundle manage Vundle (required)
Plugin 'gmarik/Vundle.vim'

" Vundle Plugins
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'sjl/gundo.vim'
Plugin 'nvie/vim-flake8'
Plugin 'scrooloose/syntastic'
Plugin 'Valloric/YouCompleteMe'

" Done with Vundle Plugins
call vundle#end()

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" ============== Pathogen Initialization =============
" This loads all the plugins in ~/.vim/bundle
" using ~/.vim/autoload/pathogen.vim
" execute pathogen#infect()

" ============== Omnicomplete Support ===============
" This adds the autocomplete function
set omnifunc=syntaxcomplete#Complete

" ================ Indentation ======================
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

filetype plugin indent on

syntax on

" ============ Solarized Colors ================
syntax enable
set background=dark

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points

" ================ Folds ============================
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

" =============== Mappings  ===========================
nmap <F8> :TagbarToggle<CR>     " Use F8 to open Tagbar
nmap <F7> :NERDTree<CR>         " Use F7 to open NERDTree
inoremap { {}<Esc>i	
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap ] <Esc>la
inoremap ) <Esc>la
inoremap } <Esc>la

" gundo
nnoremap <F5> :GundoToggle<CR>

" Flake8
nnoremap <F8> :call Flake8()<CR>

" =============== Go ================================
" These settings are for Go-lang specific features
" autocmd FileType go autocmd BufWritePre <buffer> Fmt	" gofmt code on save
" autocmd FileType go compiler go     " Always enable compiler plugin

" ================ Rust ============================
" These settings are for Rust-lang specific features
" and Racer auto-complete
let g:racer_cmd = "/home/kevin/.bin/racer"
let $RUST_SRC_PATH="/usr/local/src/rust/src"

" =============== Python ===========================
" These settings are for Python and Flake8 settings
autocmd FileType python map <buffer> <F8> :call Flake8()<CR>
