gpg_key_id: 17218E4B3692F01A
# Default shell (supported: fish, zsh, bash)
# This also determines other things like shell
# helpers and themes
default_shell: fish

# Type of Machine (can pick multiple)
work_machine: False
desktop_machine: False
gaming_machine: False
development_machine: False
laptop_machine: False
server_machine: False

# For GUI machines only
gui_kde: True

# Individual Components (can pick multiple)
desktop_component_npm: True
desktop_component_flatpak: True
desktop_component_flatpak_flathub: True
desktop_component_snap: True
desktop_component_pip: True
desktop_component_flathub: True
desktop_component_dotfiles: True
desktop_component_fish: True
desktop_component_fish_oh_my_fish: True
desktop_component_zsh: True
desktop_component_zsh_oh_my_zsh: True
desktop_component_rtv: True
desktop_component_asciinema: True
desktop_component_tilix: True
desktop_component_keybase: True
desktop_component_dropbox: True
desktop_component_buttercup: True
desktop_component_slack: True
desktop_component_signal: True
desktop_component_telegram: True
desktop_component_mpv: True
desktop_component_discord: True
desktop_component_timeshift: True
desktop_component_chrome: True
development_component_git: True
development_component_rust: True
development_component_rust_cargo_extras: True
development_component_vscode: True
development_component_gpg: True
development_component_fonts_firacode: True
developmenet_component_meld: True
development_component_clion: True
development_component_gitkraken: True
development_component_common_projects: True
gui_component_kubuntu_backports: True
gaming_component_steam: True
laptop_component_tlp: True
laptop_component_powertop: True
server_component_ssh: True
server_component_vim: True
work_component_vmware: True
work_component_vpnarea: True
work_component_standard_notes: True
work_component_lxd: True
work_component_docker: True
work_component_swapfile: True