---
- name: Create common directories
  file:
    path: "/home/kevin/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - .build
    - .tmp
    - .local/bin
    - .bin
    - Projects

- name: Fix $PATH for common directories (FISH)
  lineinfile:
    path: "/home/kevin/.config/fish/config.fish"
    line: "set -gx PATH /home/kevin/{{ item }} $PATH"
  with_items:
    - .bin
    - .local/bin
  when:
    - default_shell == "fish"

- name: Fix $PATH for common directories (ZSH)
  lineinfile:
    path: "/home/kevin/.zshrc"
    line: "export PATH=$HOME/{{ item }}:$PATH"
  with_items:
    - .bin
    - .local/bin
  when:
    - default_shell == "zsh"