---
- name: Install Common Packages (Ubuntu)
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - curl 
    - xclip
  when: 
    - ansible_facts.ansible_distribution == "Ubuntu"
#tilix fonts-firacode git zsh vim meld 