---
- name: update the system (Ubuntu)
  apt:
    name: "*"
    state: latest
    update_cache: yes
  when: 
    - ansible_facts.ansible_distribution == "Ubuntu"

- name: update the system (Fedora)
  dnf:
    name: "*"
    state: latest
  when: 
    - ansible_facts.ansible_distribution == "Fedora"
