---
- name: Add Flatpak PPA (Ubuntu)
  apt_repository:
    repo: ppa:alexlarsson/flatpak 
  when: 
    - ((ansible_facts.ansible_distribution == "Ubuntu") and (desktop_machine or desktop_component_flatpak)

- name: Install Flatpak (Ubuntu)
  apt:
    name: flatpak
    state: latest
    update_cache: yes
  when: 
    - ((ansible_facts.ansible_distribution == "Ubuntu") and (desktop_machine or desktop_component_flatpak)

- name: Install Flatpak (Ubuntu)
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  when: 
    - ((ansible_facts.ansible_distribution == "Ubuntu") and (desktop_machine or desktop_component_flatpak_flathub)
    