---
- name: Install tilix (Ubuntu)
  apt:
    name: tilix
    state: latest
    update_cache: yes
  when: 
    -|
     (ansible_facts.ansible_distribution == "Ubuntu") and 
     (gui_machine or gui_component_tilix)

- name: Create symbolic link to fix tilix (Ubuntu)
  file:
    src: /etc/profile.d/vte.sh
    dest: "/etc/profile.d/vte-2.91.sh"
    state: link
  when: 
    -| 
    (ansible_facts.ansible_distribution == "Ubuntu") and 
    (gui_machine or gui_component_tilix)

- name: Install mpv player (Ubuntu)
  apt:
    name: mpv
    state: latest
  when: 
    -| 
    (ansible_facts.ansible_distribution == "Ubuntu") and 
    (gui_machine or gui_component_mpv)

- name: Install Discord (Flatpak)
  flatpak:
    name: com.discordapp.Discord
    state: present
  when: 
    - desktop_machine or desktop_component_discord

- name: Install Slack (Flatpak)
  flatpak:
    name: com.slack.Slack
    state: present
  when: 
    - desktop_machine or desktop_component_slack

- name: Install Signal (Flatpak)
  flatpak:
    name: org.signal.Signal
    state: present
  when: 
    - desktop_machine or desktop_component_signal

- name: Install Telegram (Flatpak)
  flatpak:
    name: org.telegram.desktop
    state: present
  when: 
    - desktop_machine or desktop_component_telegram

- name: Install Dropbox (Flatpak)
  flatpak:
    name: com.dropbox.Client
    state: present
  when: 
    - desktop_machine or desktop_component_dropbox
- name: Install pip (Ubuntu)
  apt:
    name: python-pip
    state: latest
  when: 
    -|
     (ansible_facts.ansible_distribution == "Ubuntu") and 
     (desktop_machine or desktop_component_pip)

- name: Install rtv (Ubuntu)
  apt:
    name: rtv
    state: latest
  when: 
    -|
     (ansible_facts.ansible_distribution == "Ubuntu") and 
     (desktop_machine or desktop_component_rtv)

- name: Download Keybase (Ubuntu)
  get_url:
    url: https://sh.rustup.rs
    dest: /home/kevin/Downloads/keybase_amd64.deb
    mode: 0740
  when: 
    -| 
    (ansible_facts.ansible_distribution == "Ubuntu") and 
    (desktop_machine or desktop_component_keybase)

- name: Install Keybase (Ubuntu)
  apt:
    deb: /home/kevin/Downloads/keybase_amd64.deb
  when: 
    -| 
    (ansible_facts.ansible_distribution == "Ubuntu") and 
    (desktop_machine or desktop_component_keybase)

- name: Install missing packages (Ubuntu)
  command: apt-get -y install -f
  when: 
    -| 
    (ansible_facts.ansible_distribution == "Ubuntu") and 
    (desktop_machine or desktop_component_keybase)

- name: Clone ASCIInema repository
  git:
    repo: https://github.com/LegNeato/asciinema-rs
    dest: /home/kevin/.build/asciinema
  when:
    -|
     (development_machine or development_component_rust) and
     (desktop_machine or desktop_component_asciinema)

- name: Build the ASCIInema Project
  command: cargo build --release
  args:
    chdir: /home/kevin/.build/asciinema
    creates: /home/kevin/.build/asciinema/target/release/asciinema
  when:
    -|
     (development_machine or development_component_rust) and
     (desktop_machine or desktop_component_asciinema)

- name: Copy the ASCIInema binary to PATH 
  command: "cp /home/kevin/.build/asciinema/target/release/asciinema /home/kevin/.local/bin"
  args:
    creates: /home/kevin/.local/bin/asciinema
  when:
    -|
     (development_machine or development_component_rust) and
     (desktop_machine or desktop_component_asciinema)


